eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # for local
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://test-service-registry:8761/eureka/
  instance:
    hostname: service-registry